// pages/gallery.vue
<script setup lang="tsx">
import { useDark } from '@vueuse/core';

const isDark = useDark();

type ImageObject = {
    src: string;
    alt?: string;
    tooltip?: string;
};

const galleryData: ImageObject[][] = [
    [
        {
            src: "/gallery/hayper/IMG_0497_EDITED.png",
            tooltip: "First art of my new main sona ever, edited to add the height"
        },
        {
            src: "/gallery/hayper/hayper_wolf.png"
        },
        {
            src: "/gallery/hayper/WOOOO.png",
            tooltip: "My friend comissioned this for me, i added VSC to the computer screen"
        },
        {
            src: "/gallery/hayper/Untitled1831_20220816162333.png"
        },
        {
            src: "/gallery/hayper/com.png",
            tooltip: "Changed moderator's group image"
        },
        {
            src: "/gallery/hayper/WolfMan.png",
        },
        {
            src: "/gallery/hayper/PURPLEE.png",
            tooltip: "*INHALES* PURPLEEEEEEEEEE"
        }
    ],
    [
        {
            src: "/gallery/old_hayper/headshot_transparent.png",
            tooltip: "My old main fursona, a black cat"
        },
        {
            src: "/gallery/old_hayper/Untitled1883_20210904174428.png"
        },
        {
            src: "/gallery/old_hayper/Untitled453_20210515144557.png"
        },
        {
            src: "/gallery/old_hayper/sketch-1593639014980.png"
        },
        {
            src: "/gallery/old_hayper/sketch-1593477463861.png"
        },
        {
            src: "/gallery/old_hayper/sketch-1593360442075.png"
        },
        {
            src: "/gallery/old_hayper/Screenshot_20211006-031117_FlipaClip.jpg"
        },
        {
            src: "/gallery/old_hayper/Screenshot_2652.png"
        },
        {
            src: "/gallery/old_hayper/Maid_Hayper.png"
        },
        {
            src: "/gallery/old_hayper/hayper(1).png"
        },
        {
            src: "/gallery/old_hayper/hayper_socc_blep.png"
        },
        {
            src: "/gallery/old_hayper/Hayper_Portrait.png"
        },
        {
            src: "/gallery/old_hayper/haykat.png"
        },
        {
            src: "/gallery/old_hayper/hayden.gif"
        },
        {
            src: "/gallery/old_hayper/Goat.png"
        },
        {
            src: "/gallery/old_hayper/femmaid hayper.png"
        },
        {
            src: "/gallery/old_hayper/20210630_002512.png"
        },
        {
            src: "/gallery/old_hayper/20201031_141531.png"
        },
        {
            src: "/gallery/old_hayper/20201006_230127.jpg"
        },
        {
            src: "/gallery/old_hayper/1837_20220726235537.png"
        },
        {
            src: "/gallery/old_hayper/1037_Sem_Titulo.png"
        },
        {
            src: "/gallery/old_hayper/472_Sem_Titulo-1.jpg"
        }
    ],
    [
        {
            src: "/gallery/other/Untitled56_20220918142849.png",
            tooltip: "Circle in a maid dress"
        }
    ]
];

const modalData = ref({
    enabled: false,
    imageData: {}
} as {
    enabled: boolean;
    imageData?: ImageObject;
});
</script>

<template>
    <div>
        <b-container fluid>
            <b-container fluid v-for="(rowData, index) in galleryData" align-content="start">
                <b-row class="row-cols-auto gx-3 gy-3 mx-3 my-3">
                    <b-col align-self="center" v-for="imageData in rowData">
                        <b-img :src="imageData.src" :alt="imageData.alt" width="256" height="256"
                            style="object-fit: scale-down; max-width: 15rem; max-height: 15rem; cursor: pointer;" lazy
                            fluid
                            @click="() => {modalData.imageData = imageData; modalData.enabled = !modalData.enabled}" />
                    </b-col>
                </b-row>
                <hr class="border border-2" :class="{'bg-light': isDark, 'bg-dark': !isDark}"
                    v-if="index != galleryData.length-1" />
            </b-container>

        </b-container>

        <b-modal v-if="modalData.imageData != null" v-model="modalData.enabled" title="Image" hide-footer>
            <b-container class="mx-1 my-1">
                <p v-if="modalData.imageData.tooltip">{{modalData.imageData.tooltip}}</p>
                <b-img align-self="center" :src="modalData.imageData.src" :alt="modalData.imageData.alt"
                    style="object-fit: scale-down;" fluid />
            </b-container>
        </b-modal>
    </div>
</template>

// src/routes/gallery.tsx
import { FC, useState } from "react";
import {
    SimpleGrid,
    Image,
    Tooltip,
    useDisclosure,
    Modal,
    ModalBody,
    ModalCloseButton,
    ModalContent,
    ModalHeader,
    ModalOverlay,
    Divider,
    Text
} from "@chakra-ui/react";

export type ImageObject = {
    src: string;
    alt?: string;
    tooltip?: string;
};

const galleryData: ImageObject[][] = [
    [
        {
            src: new URL("/gallery/hayper/IMG_0497_EDITED.png", import.meta.url).href,
            tooltip: "First art of my new main sona ever, edited to add the height"
        },
        {
            src: new URL("/gallery/hayper/hayper_wolf.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/hayper/WOOOO.png", import.meta.url).href,
            tooltip: "My friend comissioned this for me, i added VSC to the computer screen"
        },
        {
            src: new URL("/gallery/hayper/Untitled1831_20220816162333.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/hayper/com.png", import.meta.url).href,
            tooltip: "Changed moderator's group image"
        },
        {
            src: new URL("/gallery/hayper/WolfMan.png", import.meta.url).href,
        }
    ],
    [
        {
            src: new URL("/gallery/old_hayper/headshot_transparent.png", import.meta.url).href,
            tooltip: "My old main fursona, a black cat"
        },
        {
            src: new URL("/gallery/old_hayper/Untitled1883_20210904174428.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/Untitled453_20210515144557.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/sketch-1593639014980.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/sketch-1593477463861.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/sketch-1593360442075.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/Screenshot_20211006-031117_FlipaClip.jpg", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/Screenshot_2652.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/Maid_Hayper.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/hayper(1).png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/hayper_socc_blep.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/Hayper_Portrait.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/haykat.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/hayden.gif", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/Goat.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/femmaid hayper.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/20210630_002512.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/20201031_141531.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/20201006_230127.jpg", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/1837_20220726235537.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/1037_Sem_Titulo.png", import.meta.url).href
        },
        {
            src: new URL("/gallery/old_hayper/472_Sem_Titulo-1.jpg", import.meta.url).href
        }
    ],
    [
        {
            src: new URL("/gallery/other/Untitled56_20220918142849.png", import.meta.url).href,
            tooltip: "Circle in a maid dress"
        }
    ]
];

const ConditionalWrapper: FC<{
    condition: boolean;
    wrapper: (children: any | any[]) => void;
    children: any | any;
}> = ({ condition, wrapper, children }) => (condition ? wrapper(children) : children);

export default function Gallery() {
    const [currentImage, setCurrentImage] = useState<ImageObject | null>(null);
    const { isOpen, onOpen, onClose } = useDisclosure();

    return (
        <>
            {galleryData.map((gridRow, gridIndex, gridArr) => (
                <div key={`grid-${gridIndex}`}>
                    <SimpleGrid
                        minChildWidth={"15rem"}
                        gap="1rem"
                        mt="1rem"
                        mb={gridIndex == gridArr.length - 1 ? "1rem" : ""}
                        mx="1rem"
                        h="fit-content"
                    >
                        {gridRow.map((image, imageIndex) => {
                            return (
                                <div key={`image-${gridIndex}-${imageIndex}`}>
                                    <ConditionalWrapper
                                        condition={image.tooltip != null}
                                        wrapper={(children: any) => <Tooltip label={image.tooltip}>{children}</Tooltip>}
                                    >
                                        <Image
                                            src={image.src}
                                            alt={image.alt}
                                            loading="lazy"
                                            objectFit={"scale-down"}
                                            boxSize={"15rem"}
                                            onClick={() => {
                                                setCurrentImage(image);
                                                onOpen();
                                            }}
                                            cursor={"pointer"}
                                        />
                                    </ConditionalWrapper>
                                </div>
                            );
                        })}
                    </SimpleGrid>
                    {gridIndex !== gridArr.length - 1 && <Divider orientation="horizontal" mt={"1rem"} />}
                </div>
            ))}

            {currentImage != null && (
                <Modal isOpen={isOpen} onClose={onClose}>
                    <ModalOverlay />
                    <ModalContent>
                        <ModalHeader>Image</ModalHeader>
                        <ModalCloseButton />
                        <ModalBody mb={"0.5rem"}>
                            {currentImage!.tooltip != null && <Text mb="1rem">{currentImage!.tooltip}</Text>}
                            <Image src={currentImage!.src} loading="lazy" />
                        </ModalBody>
                    </ModalContent>
                </Modal>
            )}
        </>
    );
}
